### ISSUE TITLE
The requirements in the conda recipe are out of date

### ISSUE THREAD

**Issue by nitramsivart** [conda-forge/google-api-python-client-feedstock#39]
Issue: The requirements in the conda recipe are out of date

E.g. the following two lines should match, but don't:

- https://github.com/conda-forge/google-api-python-client-feedstock/blob/8585bdf90e5606005269a59640c07c5d3a96d7a3/recipe/meta.yaml#L23
- https://github.com/googleapis/google-api-python-client/blob/ee53b3b32a050874ba4cfb491fb384f94682c824/setup.py#L42

As a result, if I `conda install google-api-python-client=1.9.1`, I don't actually get the proper version `google-auth>1.16`, but instead I get `google-auth=1.14.1`

Is this because some automated build hook is broken?

**Comment by busunkim96** [comment]
It looks like the requirements are manually updated . See https://github.com/conda-forge/google-api-python-client-feedstock/pull/30/commits/797ae4b4baf5f28087c5a295554716aeda1e07d5 for example
